export const actionTypes = {
  COMPLETE_TASK: "COMPLETE_TASK",
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  SET_FILTER: "SET_FILTER",
  SAVE_EDITED: "SAVE_EDITED",
  SHOW_ACTIVE: "SHOW_ACTIVE",
  SHOW_DONE: "SHOW_DONE",
  SHOW_ALL: "SHOW_ALL",
};
